sudo: false

language: c

env:
  global:
  - GHC_VERSION=8.2.2
  - ENCRYPTION_LABEL: "0ac6d80b3689"
  - COMMIT_AUTHOR_EMAIL: "travis@anis.com.au"

branches:
  only:
  - master

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-head
    - ghc-8.2.2

install:
- stack --no-terminal build

script:
- stack --no-terminal exec site build

after_script:
- ./after_install.sh



# Adding a CNAME file, so our custom domain works with github 
# - echo "blog.${GH_USER}.com" > CNAME  
# - git config --global user.email "travis@anis.com.au"
# - git config --global user.name "Travis CI"
# - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
# - git init  
# - git remote add github https://${GH_USER}:${GH_TOKEN}@${REMOTE}
# - git add --all
# - git status
# - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
# # We don't care about commits to the master as a completely new site would be generated everytime  
# - git push github master:master -f 2>&1 | grep -v http


# ghc:
#   - "8.4.1"

# script: bash ./deploy.sh


# before_install:
# # Download and unpack the stack executable
# - mkdir -p ~/.local/bin
# - export PATH=$HOME/.local/bin:$PATH
# - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'