ghc:
  - "8.2.1"

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "0ac6d80b3689"
  - COMMIT_AUTHOR_EMAIL: "travis@anis.com.au"

# sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- ./before-install.sh